# Generated by Django 4.2.8 on 2025-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('pending', 'Chờ xác nhận')], default='pending', max_length=20),
        ),
    ]
