# Generated by Django 4.2.8 on 2025-10-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksale_app', '0002_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(help_text='Tên khách hàng', max_length=255)),
                ('email', models.EmailField(help_text='Email', max_length=100)),
                ('phone', models.CharField(help_text='Số điện thoại', max_length=15)),
                ('address', models.CharField(help_text='Địa chi', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(help_text='Mô tả')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(help_text='Mô tả')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(help_text='Tên khách hàng', max_length=255)),
                ('email', models.EmailField(help_text='Email', max_length=100)),
                ('phone', models.CharField(help_text='Số điện thoại', max_length=15)),
                ('address', models.CharField(help_text='Địa chi', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportOrder_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.importorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='importorder',
            name='product',
            field=models.ManyToManyField(through='booksale_app.ImportOrder_Item', to='booksale_app.product'),
        ),
        migrations.AddField(
            model_name='importorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.supplier'),
        ),
        migrations.CreateModel(
            name='ExportOrder_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exportOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.exportorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booksale_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='exportorder',
            name='product',
            field=models.ManyToManyField(through='booksale_app.ExportOrder_Item', to='booksale_app.product'),
        ),
    ]
