# Generated by Django 4.2.8 on 2025-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0003_employee_exportorder_importorder_customer_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('pending', 'Chờ xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
