# Generated by Django 4.2.8 on 2025-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0004_order_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_name',
            field=models.CharField(help_text='Tên nhà cung cấp', max_length=255),
        ),
    ]
