# Generated by Django 4.2.8 on 2025-11-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0005_remove_supplier_user_review_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
