# Generated by Django 4.2.8 on 2025-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0006_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('pending', 'Chờ xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], default='pending', max_length=20),
        ),
    ]
