# Generated by Django 4.2.8 on 2025-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0007_remove_category_slug_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng'),
        ),
    ]
