# Generated by Django 4.2.8 on 2025-11-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0009_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
