# Generated by Django 4.2.8 on 2025-11-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksale_app', '0011_replyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Message from admin', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReplyReview',
        ),
    ]
