# Generated by Django 4.2.8 on 2025-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0012_review_reply_message_review_reply_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorder',
            name='note',
            field=models.TextField(blank=True, help_text='Mô tả', null=True),
        ),
    ]
