# Generated by Django 4.2.8 on 2025-12-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale_app', '0014_alter_cart_item_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
    ]
